### ISSUE TITLE
Doesn't work in Engines

### ISSUE THREAD

**Issue by lougreenwood** [Windvis/ember-router-service-refresh-polyfill#11]
Thanks for this great polyfill!

I just tried it out in an Ember Engine and noticed that it doesn't work, here's what I get in the console:

![Screen Shot 57](https://user-images.githubusercontent.com/12051736/132405859-c245bf8a-47b9-464c-b85a-eb005b198007.png)

I'm wondering if looking up on the application doesn't provide the proper router service for an engine?

**Comment by lougreenwood** [comment]
Some more info - I can get past the error above if I also install https://github.com/villander/ember-engines-router-service, however the `refresh` method then doesn't exist on the router service, so I suppose the wrong router service is getting poly filled.

**Comment by Windvis** [comment]
Hey @lougreenwood!

I don't have any experience with engines but my understanding is that engines don't use the host app's router service directly. So installing this polyfill inside an engine isn't the way to go I think. 

The service that the ember-engines-router-service provides is not the same service from the host app, so that's why it won't have the refresh method.

I noticed [these lines of code](https://github.com/villander/ember-engines-router-service/blob/433a89f507fc78b6b6db515acc6d1f5c78bae555/addon/services/engine-router-service.js#L52-L54) in the addon. Does `this.router.externalRouter.refresh()` work if you install the polyfill in the host app? If that works you could extend the ember-engines-router-service to add a refresh and refreshExternal method similar to the other methods in there.

**Comment by Windvis** [comment]
Closing since I don't think it's an issue with the polyfill itself. Feel free to open it again if you think otherwise!
